POST https://{{host}}:{{port}}/auth/signUp
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "email": "{{email}}"
}

###

POST https://{{host}}:{{port}}/auth/signIn
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

POST https://{{host}}:{{port}}/auth/signOut
Authorization: Bearer {{token}}

###

POST https://{{host}}:{{port}}/auth/refresh
Authorization: Bearer {{token}}

###

