GET https://localhost:5000/service/status
Authorization: Bearer {{token}}

###

GET https://localhost:5000/service/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "fun-client"
}

###

POST https://localhost:5000/service/start
Authorization: Bearer {{token}}

###

POST https://localhost:5000/service/start
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "fun-client"
}

###

POST https://localhost:5000/service/stop
Authorization: Bearer {{token}}

###

POST https://localhost:5000/service/stop
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "fun-client"
}

###
